[package]
name = "jeffd"
version = "6.0.1"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
jeff-project = { path = "../jeff-project" }
libc = "0.2"
notify = "9.0.0-rc.4"
serde_json = "1"
signal-hook = "0.3"
thiserror = "2"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
